Bug#24579061 UPGRADE TO BOOST 1.62.0
Upgrade dependency to 1.62.0 and remove those patches for Boost 1.60.0
that are already included in 1.62.0. Add patches to fix bugs in Boost
1.62.0.

Also add patch to boost/exception/info.hpp to fix error C4099 (type
first declared struct, then class) in Visual Studio. Add
BOOST_PATCHES_DIR to the include path in X plugin.

Remove test case for bug #20357097 since it no longer returns an
error, but instead takes a long time to complete.